import java.nio.file.Path

plugins {
    id 'java'
    id 'github' version '1.0'
}

github_plugins {
    github 'Olafcio1/gradle-shade-plugin' version '1.0'
}

group = 'pl.olafcio.tedge'
version = project.version

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    compileOnly files(Path.of("${System.getenv("USERPROFILE")}/.gradle/caches/Tedge-ML/${project.minecraft}/client-only-transformed.jar"))
    compileOnly files(Path.of("${System.getenv("USERPROFILE")}/.gradle/caches/Tedge-ML/${project.minecraft}/server-only-transformed.jar"))
    compileOnly files(Path.of("${System.getenv("USERPROFILE")}/.gradle/caches/Tedge-ML/${project.minecraft}/shared-transformed.jar"))

    implementation 'com.google.code.gson:gson:2.8.9'
    implementation 'tools.jackson.core:jackson-core:3.2.1'
    implementation 'tools.jackson.core:jackson-databind:3.2.1'
    implementation 'org.jspecify:jspecify:1.0.0'
    implementation 'org.ow2.asm:asm:9.10.1'
    implementation 'org.ow2.asm:asm-tree:9.10.1'
    implementation 'org.yaml:snakeyaml:2.2'

    implementation github("TedgeMC/Tedge-Mixin",   version: project.mixin, file: "TedgeMixin-${project.mixin}.jar")
    implementation github("TedgeMC/AccessEditors", version: project.accesseditors)
}

test {
    useJUnitPlatform()
}

jar {
    manifest {
        attributes("Main-Class": "pl.olafcio.tedge.Main",
                   "Premain-Class": 'pl.olafcio.tedge.Agent',
                   "Can-Redefine-Classes": 'true',
                   "Can-Retransform-Classes": 'true',
                   "Can-Set-Native-Method-Prefix": 'true')
    }

    shade {
        runtimeClasspath("TedgeMixin-(.*)")
        runtimeClasspath("AccessEditors-(.*)")
    }

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
