plugins {
    id 'java'
}

group = 'pl.olafcio.tedge'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    implementation rootProject.project(":src-jargen")

    implementation 'com.google.code.gson:gson:2.8.9'
    implementation 'org.jspecify:jspecify:1.0.0'
}

test {
    useJUnitPlatform()
}

jar {
    manifest {
        attributes("Main-Class": "pl.olafcio.tedge.launcher.Main")
    }
}
